In [1]:
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import pandas as pd
from ipywidgets import interact, interactive, fixed, interact_manual
import ipywidgets as widgets

In [2]:
df = pd.read_csv('data/combined_tweets.csv')
users = df["user"].unique()

In [3]:
def get_engagements(df):
    viz_df = df.loc[df["has_viz"] == True]
    no_viz_df = df.loc[df["has_viz"] == False]
    
    viz_retweets = viz_df["retweets"].sum()
    viz_replies = viz_df["replies"].sum()
    viz_likes = viz_df["likes"].sum()
    viz_quotes = viz_df["quotes"].sum()
    
    no_viz_retweets = no_viz_df["retweets"].sum()
    no_viz_replies = no_viz_df["replies"].sum()
    no_viz_likes = no_viz_df["likes"].sum()
    no_viz_quotes = no_viz_df["quotes"].sum()
    
    viz_engagements = viz_retweets + viz_replies + viz_likes + viz_quotes
    no_viz_engagements = no_viz_retweets + no_viz_replies + no_viz_likes + no_viz_quotes
    
    total_engagements = viz_engagements + no_viz_engagements
    
    non_viz_tweets = len(no_viz_df)
    viz_tweets = len(viz_df)
    
    print("viz tweets:", viz_tweets)
    print("non viz tweets:", non_viz_tweets)
    
    print("visualization tweet engagements: ", viz_engagements)
    print("no visualization tweet engagements: ", no_viz_engagements)
    print("total engagements: ", total_engagements)
    
    return total_engagements

In [4]:
#https://stackoverflow.com/questions/34020789/ipywidgets-dropdown-widgets-what-is-the-onchange-event

dropdown = widgets.Dropdown(
    options=users,
    value = "BNONews",
    description='Author: ',
)

disp_df = df.loc[df["user"] == dropdown.value]
get_engagements(disp_df)

def on_change(change):
    if change['type'] == 'change' and change['name'] == 'value':
        print("---------------------------------")
        print("changed to %s" % change['new'])
        disp_df = df.loc[df["user"] == change['new']]
        get_engagements(disp_df)
        
        
dropdown.observe(on_change)

display(dropdown)

viz tweets: 6
non viz tweets: 62
visualization tweet engagements:  164912
no visualization tweet engagements:  154530
total engagements:  319442

Dropdown(description='Author: ', options=('BNONews', 'CDCGov', 'CNN', 'DrEricDing', 'DrTomFrieden', 'JeromeAda…

In [5]:
disp_df

,tweet_id,user,text,date,retweets,replies,likes,quotes,has_viz
0,1312029170772381697,BNONews,"RT @BNODesk: NEW: Trump is experiencing ""mild ...",10/02/2020 13:58:25,276,0,0,0,False
1,1323902358808649731,BNONews,"Republican David Andahl, who died from COVID-1...",11/04/2020 08:18:13,11378,2020,41068,25607,False
2,1353045636472516610,BNONews,RT @BNODesk: Legendary talk show host Larry Ki...,01/23/2021 18:23:12,106,0,0,0,True
3,1222998147422736384,BNONews,BREAKING: Italy cancels all flights to and fro...,01/30/2020 21:40:55,513,23,777,155,False
4,1222968727869775872,BNONews,BREAKING: World Health Organization declares n...,01/30/2020 19:44:01,1031,87,1377,243,False
...,...,...,...,...,...,...,...,...,...
63,1236049460154818561,BNONews,RT @BNODesk: BREAKING: SXSW has been canceled ...,03/06/2020 22:02:10,539,0,0,0,False
64,1235254196624134144,BNONews,RT @BNODesk: BREAKING: Release of the new Jame...,03/04/2020 17:22:05,536,0,0,0,False
65,1235179527006978049,BNONews,RT @BNODesk: BREAKING: Germany's health minist...,03/04/2020 12:25:22,1261,0,0,0,False
66,1247242039860834304,BNONews,RT @BNODesk: BREAKING: British Prime Minister ...,04/06/2020 19:17:29,2511,0,0,0,False
67,1287144321649717248,BNONews,RT @BNODesk: BREAKING: North Korea reports fir...,07/25/2020 21:54:54,1492,0,0,0,False

In [6]:
print(disp_df["retweets"].sum())

109954